version: '3.8'

name: mtb-races-backend-dist
services:
    postgres:
        image: postgres:16
        container_name: mtb-races-backend-dist-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mtb_races_db
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mtb-races-backend-dist-app
        ports:
            - '8002:8002'
        env_file:
            - .env
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - .:/home/pptruser
            - /home/pptruser/node_modules
            - pnpm-cache:/home/pptruser/.pnpm
        depends_on:
            postgres:
                condition: service_healthy
        command: pnpm run start

volumes:
    postgres_data:
    pnpm-cache:
