version: "3.8"

name: mtb-races-backend-test
services:
    postgres:
        image: postgres:16
        container_name: mtb-races-backend-test-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mtb_races_test_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data_test:/var/lib/postgresql/data

volumes:
    postgres_data_test:
