FROM ghcr.io/puppeteer/puppeteer:latest

USER root
WORKDIR /home/pptruser

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN chown -R pptruser:pptruser /home/pptruser
USER pptruser

EXPOSE 8002
CMD ["pnpm", "run", "dev"]