# .github/workflows/deploy.yml
name: Deploy to Azure
on:
    push:
        branches: [master]

env:
    AZURE_WEBAPP_NAME: switchback-dev-api
    AZURE_WEBAPP_PACKAGE_PATH: '.'
    NODE_VERSION: '22.x'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'pnpm'

            - name: Install dependencies and build
              run: |
                  pnpm ci
                  pnpm build

            - name: Upload artifact for deployment
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.AZURE_WEBAPP_NAME }}
                  path: .
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'development'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: ${{ env.AZURE_WEBAPP_NAME }}

            - name: 'Deploy to Azure WebApp'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
