# .github/workflows/deploy.yml
name: Deploy to Azure
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build and push image
              uses: azure/docker-login@v1
              with:
                  login-server: mtbracesdev.azurecr.io
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build and push
              run: |
                  docker build -t mtbracesdev.azurecr.io/switchback-backend:${{ github.sha }} .
                  docker push mtbracesdev.azurecr.io/switchback-backend:${{ github.sha }}

            - name: Deploy to Container Apps
              uses: azure/container-apps-deploy-action@v1
              with:
                  containerAppName: switchback-dev-env
                  resourceGroup: switchback-dev
                  imageToDeploy: mtbracesdev.azurecr.io/switchback-backend:${{ github.sha }}
