name: Test

on:
    pull_request:
        branches:
            - master
env:
    DATABASE_URL: postgres://postgres:postgres@localhost:5433/mtb_races_test_db
    FRONTEND_BASE_URL: http://localhost:3000
    PORT: 8002
jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: 'Run docker compose'
              uses: hoverkraft-tech/compose-action@v2.0.1
              with:
                  compose-file: './docker-compose-test.yml'

            - name: 'Install PNPM'
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: 'Install Node.js'
              uses: actions/setup-node@v4
              with:
                  node-version-file: 'package.json'
                  cache: 'pnpm'

            - name: 'Install Dependencies'
              run: pnpm install

            - name: 'Install Puppeteer Dependencies'
              run: pnpm puppeteer browsers install chrome

            - name: Disable AppArmor
              run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

            - name: 'Create env file'
              run: |
                  touch .env.test
                  echo DATABASE_URL=$DATABASE_URL
                  echo FRONTEND_BASE_URL=$FRONTEND_BASE_URL
                  echo PORT=$PORT

            - name: 'Run Tests'
              run: pnpm vitest --coverage.enabled true

            - name: 'Report Coverage'
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                  file-coverage-mode: all
